[project]
name = "sarverott"
version = "0.1.0"
description = "my forest of thoughts"
authors = ["Sett Sarverott <sarverott@gmail.com>"]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "solders>=0.27.1",
]

[dependency-groups]
dev = [
    "go-task-bin>=3.49.1",
    "notebook>=7.5.5",
]
